function dfdth = dfdthFunc(in1,in2,in3,in4)
%DFDTHFUNC
%    DFDTH = DFDTHFUNC(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Nov-2016 18:14:24

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
thd = in4(3,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t2 = th1+th2+th3+th4;
t3 = th1+th2;
t4 = th1+th2+th3;
t5 = cos(t2);
t6 = L4.*t5;
t7 = cos(t3);
t8 = L2.*t7;
t9 = cos(th1);
t10 = L1.*t9;
t11 = cos(t4);
t12 = L3.*t11;
t13 = sin(t2);
t14 = L4.*t13;
t15 = sin(t3);
t16 = L2.*t15;
t17 = sin(th1);
t18 = L1.*t17;
t19 = sin(t4);
t20 = L3.*t19;
t21 = sin(thd);
t22 = cos(thd);
t23 = t5.*t21;
t28 = t13.*t22;
t24 = t23-t28;
t25 = t5.*t22;
t26 = t13.*t21;
t27 = t25+t26;
t29 = t25+t26-1.0;
t30 = t24.*t29.*4.0;
t31 = t6+t8+t10+t12+xb-xd;
t32 = t14+t16+t18+t20+yb-yd;
dfdth = [t30+t32.*(t6+t8+t10+t12).*2.0-t31.*(t14+t16+t18+t20).*2.0-t24.*t27.*4.0,t30-t24.*t27.*4.0+t32.*(t6+t8+t12).*2.0-t31.*(t14+t16+t20).*2.0,t30+t32.*(t6+t12).*2.0-t31.*(t14+t20).*2.0-t24.*t27.*4.0,t30-t24.*t27.*4.0+L4.*t5.*t32.*2.0-L4.*t13.*t31.*2.0];
