function dfdth = dfdthFunc(in1,in2,in3,in4)
%DFDTHFUNC
%    DFDTH = DFDTHFUNC(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    08-Nov-2016 09:45:54

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
thd = in4(3,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t2 = th1+th2+th3;
t3 = cos(t2);
t4 = sin(thd);
t5 = sin(t2);
t6 = cos(thd);
t7 = t3.*t4;
t25 = t5.*t6;
t8 = t7-t25;
t9 = t3.*t6;
t10 = t4.*t5;
t11 = th1+th2;
t12 = cos(t11);
t13 = L2.*t12;
t14 = cos(th1);
t15 = L1.*t14;
t16 = L3.*t3;
t17 = sin(t11);
t18 = L2.*t17;
t19 = sin(th1);
t20 = L1.*t19;
t21 = L3.*t5;
t22 = t13+t15+t16+xb-xd;
t23 = t18+t20+t21+yb-yd;
t24 = t9+t10;
t26 = t9+t10-1.0;
t27 = t8.*t26.*4.0;
dfdth = [t27-t8.*t24.*4.0+t23.*(t13+t15+t16).*2.0-t22.*(t18+t20+t21).*2.0,t27+t23.*(t13+t16).*2.0-t22.*(t18+t21).*2.0-t8.*t24.*4.0,t27-t8.*t24.*4.0+L3.*t3.*t23.*2.0-L3.*t5.*t22.*2.0];
