function f = fFunc(in1,in2,in3,in4)
%FFUNC
%    F = FFUNC(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    29-Oct-2016 20:10:13

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
thd = in4(3,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t3 = th1+th2;
t4 = sin(t3);
t2 = yb-yd+L2.*t4+L1.*sin(th1);
t6 = sin(thd);
t7 = cos(t3);
t8 = cos(thd);
t5 = -t4.*t8+t6.*t7;
t9 = t4.*t6+t7.*t8-1.0;
t10 = xb-xd+L2.*t7+L1.*cos(th1);
f = t2.^2+t5.^2.*2.0+t9.^2.*2.0+t10.^2;
