function g_st = fkFunc(in1,in2,in3)
%FKFUNC
%    G_ST = FKFUNC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Nov-2016 13:32:07

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2;
t3 = th1+th2+th3;
t4 = cos(th1);
t5 = cos(t2);
t6 = L1.*t4;
t7 = L2.*t5;
t8 = cos(t3);
t9 = sin(th1);
t10 = sin(t2);
t11 = sin(t3);
t12 = L1.*t9;
t13 = L2.*t10;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t4,t9,0.0,0.0,-t9,t4,0.0,0.0,0.0,0.0,1.0,0.0,t6+xb,t12+yb,zb,1.0,t5,t10,0.0,0.0,-t10,t5,0.0,0.0,0.0,0.0,1.0,0.0,t6+t7+xb,t12+t13+yb,zb,1.0,t8,t11,0.0,0.0,-t11,t8,0.0,0.0,0.0,0.0,1.0,0.0,t6+t7+xb+L3.*t8,t12+t13+yb+L3.*t11,zb,1.0],[4,4,4]);
