function g_st = fkFunc(in1,in2,in3)
%FKFUNC
%    G_ST = FKFUNC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Nov-2016 18:14:24

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2;
t3 = th1+th2+th3;
t4 = th1+th2+th3+th4;
t5 = cos(th1);
t6 = cos(t2);
t7 = L1.*t5;
t8 = L2.*t6;
t9 = cos(t3);
t10 = cos(t4);
t11 = L3.*t9;
t12 = sin(th1);
t13 = sin(t2);
t14 = sin(t3);
t15 = sin(t4);
t16 = L1.*t12;
t17 = L2.*t13;
t18 = L3.*t14;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t5,t12,0.0,0.0,-t12,t5,0.0,0.0,0.0,0.0,1.0,0.0,t7+xb,t16+yb,zb,1.0,t6,t13,0.0,0.0,-t13,t6,0.0,0.0,0.0,0.0,1.0,0.0,t7+t8+xb,t16+t17+yb,zb,1.0,t9,t14,0.0,0.0,-t14,t9,0.0,0.0,0.0,0.0,1.0,0.0,t7+t8+t11+xb,t16+t17+t18+yb,zb,1.0,t10,t15,0.0,0.0,-t15,t10,0.0,0.0,0.0,0.0,1.0,0.0,t7+t8+t11+xb+L4.*t10,t16+t17+t18+yb+L4.*t15,zb,1.0],[4,4,5]);
