function g_tau = g_torqueFunc3(in1,in2,in3)
%G_TORQUEFUNC3
%    G_TAU = G_TORQUEFUNC3(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    29-Nov-2016 11:40:42

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = L1.*t2;
t4 = th1+th2;
t5 = cos(t4);
t6 = L2.*t5;
t7 = th1+th2+th3;
t8 = cos(t7);
t9 = L3.*t8.*(1.0./2.0);
t10 = L2.*(1.7e1./4.0e1);
t11 = t10+9.0./2.5e1;
t12 = 1.0./t11;
t13 = L2.*4.16925;
t14 = t13+3.5316;
t15 = L2.*(9.0./2.5e1);
t16 = L2.^2;
t17 = t16.*(1.7e1./8.0e1);
t18 = t15+t17;
g_tau = [t14.*(t3+t5.*t12.*t18)+L3.*(t3+t6+t9).*4.16925+(t2.*(L1.*4.16925+3.5316).*(L1.*(9.0./2.5e1)+L1.^2.*(1.7e1./8.0e1)))./(L1.*(1.7e1./4.0e1)+9.0./2.5e1),L3.*(t6+t9).*4.16925+t5.*t12.*t14.*t18,L3.^2.*t8.*2.084625];
