function g_tau = g_torqueFunc2(in1,in2,in3)
%G_TORQUEFUNC2
%    G_TAU = G_TORQUEFUNC2(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Nov-2016 12:02:50

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = th1+th2;
t4 = cos(t3);
g_tau = [L2.*(L1.*t2+L2.*t4.*(1.0./2.0)).*4.16925+(t2.*(L1.*4.16925+3.5316).*(L1.*(9.0./2.5e1)+L1.^2.*(1.7e1./8.0e1)))./(L1.*(1.7e1./4.0e1)+9.0./2.5e1),L2.^2.*t4.*2.084625];
