function g_tau = g_torqueFunc1(th1,L1,in3)
%G_TORQUEFUNC1
%    G_TAU = G_TORQUEFUNC1(TH1,L1,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    29-Nov-2016 11:40:37

g_tau = L1.^2.*cos(th1).*2.084625;
