function gd_tau = gd_torqueFunc2(in1,in2,in3)
%GD_TORQUEFUNC2
%    GD_TAU = GD_TORQUEFUNC2(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Nov-2016 12:02:50

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = sin(t3);
t5 = L1.*4.16925;
t6 = t5+3.5316;
t7 = cos(th1);
t8 = L1.*(1.7e1./4.0e1);
t9 = t8+9.0./2.5e1;
t10 = 1.0./t9;
t11 = L1.*(9.0./2.5e1);
t12 = L1.^2;
t13 = t12.*(1.7e1./8.0e1);
t14 = t11+t13;
t15 = L2.^2;
t16 = cos(t3);
t17 = L2.*t16.*4.16925;
gd_tau = reshape([L2.*(L1.*t2+L2.*t4.*(1.0./2.0)).*(-4.16925)-t2.*t6.*t10.*t14,t4.*t15.*(-2.084625),t4.*t15.*(-2.084625),t4.*t15.*(-2.084625),L2.*t7.*4.16925+t6.*t7+t7.*t10.*t14.*4.16925-t6.*t7.*1.0./t9.^2.*t14.*(1.7e1./4.0e1),0.0,t17+L1.*t7.*4.16925,t17],[2,4]);
