function g_st = fkFunc1(th1,L1,in3,effOffset)
%FKFUNC1
%    G_ST = FKFUNC1(TH1,L1,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:11

xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = effOffset+th1;
t3 = sin(t2);
t4 = cos(t2);
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t4,t3,0.0,0.0,-t3,t4,0.0,0.0,0.0,0.0,1.0,0.0,xb+L1.*cos(th1),yb+L1.*sin(th1),zb,1.0],[4,4,2]);
