function g_st = fkFunc1(th1,L1,in3,effOffset)
%FKFUNC1
%    G_ST = FKFUNC1(TH1,L1,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:45:16

xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = cos(effOffset);
t3 = sin(th1);
t4 = cos(th1);
t5 = sin(effOffset);
t6 = t2.*t4;
t7 = t6-t3.*t5;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t7,t2.*t3+t4.*t5,0.0,0.0,-t2.*t3-t4.*t5,t7,0.0,0.0,0.0,0.0,1.0,0.0,xb+L1.*t4,yb+L1.*t3,zb,1.0],[4,4,2]);
