function g_st = fkFunc3(in1,in2,in3,effOffset)
%FKFUNC3
%    G_ST = FKFUNC3(IN1,IN2,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:07

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2+th3;
t3 = th1+th2;
t4 = cos(t2);
t5 = sin(effOffset);
t6 = sin(t2);
t7 = cos(effOffset);
t8 = cos(th1);
t9 = cos(t3);
t10 = L1.*t8;
t11 = L2.*t9;
t12 = sin(th1);
t13 = sin(t3);
t14 = t4.*t7;
t15 = t14-t5.*t6;
t16 = L1.*t12;
t17 = L2.*t13;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t8,t12,0.0,0.0,-t12,t8,0.0,0.0,0.0,0.0,1.0,0.0,t10+xb,t16+yb,zb,1.0,t9,t13,0.0,0.0,-t13,t9,0.0,0.0,0.0,0.0,1.0,0.0,t10+t11+xb,t16+t17+yb,zb,1.0,t15,t4.*t5+t6.*t7,0.0,0.0,-t4.*t5-t6.*t7,t15,0.0,0.0,0.0,0.0,1.0,0.0,t10+t11+xb+L3.*t4,t16+t17+yb+L3.*t6,zb,1.0],[4,4,4]);
