function g_st = fkFunc6(in1,in2,in3,effOffset)
%FKFUNC6
%    G_ST = FKFUNC6(IN1,IN2,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Nov-2016 14:23:46

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
L6 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
th6 = in1(6,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2+th3+th4+th5+th6;
t3 = th1+th2;
t4 = th1+th2+th3;
t5 = th1+th2+th3+th4;
t6 = th1+th2+th3+th4+th5;
t7 = cos(t2);
t8 = sin(effOffset);
t9 = sin(t2);
t10 = cos(effOffset);
t11 = cos(th1);
t12 = cos(t3);
t13 = L1.*t11;
t14 = L2.*t12;
t15 = cos(t4);
t16 = cos(t5);
t17 = L3.*t15;
t18 = L4.*t16;
t19 = cos(t6);
t20 = L5.*t19;
t21 = sin(th1);
t22 = sin(t3);
t23 = sin(t4);
t24 = sin(t5);
t25 = sin(t6);
t26 = t7.*t10;
t27 = t26-t8.*t9;
t28 = L1.*t21;
t29 = L2.*t22;
t30 = L3.*t23;
t31 = L4.*t24;
t32 = L5.*t25;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t11,t21,0.0,0.0,-t21,t11,0.0,0.0,0.0,0.0,1.0,0.0,t13+xb,t28+yb,zb,1.0,t12,t22,0.0,0.0,-t22,t12,0.0,0.0,0.0,0.0,1.0,0.0,t13+t14+xb,t28+t29+yb,zb,1.0,t15,t23,0.0,0.0,-t23,t15,0.0,0.0,0.0,0.0,1.0,0.0,t13+t14+t17+xb,t28+t29+t30+yb,zb,1.0,t16,t24,0.0,0.0,-t24,t16,0.0,0.0,0.0,0.0,1.0,0.0,t13+t14+t17+t18+xb,t28+t29+t30+t31+yb,zb,1.0,t19,t25,0.0,0.0,-t25,t19,0.0,0.0,0.0,0.0,1.0,0.0,t13+t14+t17+t18+t20+xb,t28+t29+t30+t31+t32+yb,zb,1.0,t27,t7.*t8+t9.*t10,0.0,0.0,-t7.*t8-t9.*t10,t27,0.0,0.0,0.0,0.0,1.0,0.0,t13+t14+t17+t18+t20+xb+L6.*t7,t28+t29+t30+t31+t32+yb+L6.*t9,zb,1.0],[4,4,7]);
