function g_st = fkFunc2(in1,in2,in3,effOffset)
%FKFUNC2
%    G_ST = FKFUNC2(IN1,IN2,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:45:19

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(effOffset);
t5 = sin(t2);
t6 = cos(effOffset);
t7 = cos(th1);
t8 = L1.*t7;
t9 = sin(th1);
t10 = t3.*t6;
t11 = t10-t4.*t5;
t12 = L1.*t9;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t7,t9,0.0,0.0,-t9,t7,0.0,0.0,0.0,0.0,1.0,0.0,t8+xb,t12+yb,zb,1.0,t11,t3.*t4+t5.*t6,0.0,0.0,-t3.*t4-t5.*t6,t11,0.0,0.0,0.0,0.0,1.0,0.0,t8+xb+L2.*t3,t12+yb+L2.*t5,zb,1.0],[4,4,3]);
