function g_st = fkFunc5(in1,in2,in3,effOffset)
%FKFUNC5
%    G_ST = FKFUNC5(IN1,IN2,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:45:38

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2+th3+th4+th5;
t3 = th1+th2;
t4 = th1+th2+th3;
t5 = th1+th2+th3+th4;
t6 = cos(t2);
t7 = sin(effOffset);
t8 = sin(t2);
t9 = cos(effOffset);
t10 = cos(th1);
t11 = cos(t3);
t12 = L1.*t10;
t13 = L2.*t11;
t14 = cos(t4);
t15 = cos(t5);
t16 = L3.*t14;
t17 = L4.*t15;
t18 = sin(th1);
t19 = sin(t3);
t20 = sin(t4);
t21 = sin(t5);
t22 = t6.*t9;
t23 = t22-t7.*t8;
t24 = L1.*t18;
t25 = L2.*t19;
t26 = L3.*t20;
t27 = L4.*t21;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t10,t18,0.0,0.0,-t18,t10,0.0,0.0,0.0,0.0,1.0,0.0,t12+xb,t24+yb,zb,1.0,t11,t19,0.0,0.0,-t19,t11,0.0,0.0,0.0,0.0,1.0,0.0,t12+t13+xb,t24+t25+yb,zb,1.0,t14,t20,0.0,0.0,-t20,t14,0.0,0.0,0.0,0.0,1.0,0.0,t12+t13+t16+xb,t24+t25+t26+yb,zb,1.0,t15,t21,0.0,0.0,-t21,t15,0.0,0.0,0.0,0.0,1.0,0.0,t12+t13+t16+t17+xb,t24+t25+t26+t27+yb,zb,1.0,t23,t6.*t7+t8.*t9,0.0,0.0,-t6.*t7-t8.*t9,t23,0.0,0.0,0.0,0.0,1.0,0.0,t12+t13+t16+t17+xb+L5.*t6,t24+t25+t26+t27+yb+L5.*t8,zb,1.0],[4,4,6]);
