function g_st = fkFunc2(in1,in2,in3,effOffset)
%FKFUNC2
%    G_ST = FKFUNC2(IN1,IN2,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:15

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = effOffset+th1+th2;
t3 = cos(th1);
t4 = L1.*t3;
t5 = sin(th1);
t6 = sin(t2);
t7 = cos(t2);
t8 = th1+th2;
t9 = L1.*t5;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t3,t5,0.0,0.0,-t5,t3,0.0,0.0,0.0,0.0,1.0,0.0,t4+xb,t9+yb,zb,1.0,t7,t6,0.0,0.0,-t6,t7,0.0,0.0,0.0,0.0,1.0,0.0,t4+xb+L2.*cos(t8),t9+yb+L2.*sin(t8),zb,1.0],[4,4,3]);
