function g_st = fkFunc6(in1,in2,in3)
%FKFUNC6
%    G_ST = FKFUNC6(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:43

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
L6 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
th6 = in1(6,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2;
t3 = th1+th2+th3;
t4 = th1+th2+th3+th4;
t5 = th1+th2+th3+th4+th5;
t6 = th1+th2+th3+th4+th5+th6;
t7 = cos(th1);
t8 = cos(t2);
t9 = L1.*t7;
t10 = L2.*t8;
t11 = cos(t3);
t12 = cos(t4);
t13 = L3.*t11;
t14 = L4.*t12;
t15 = cos(t5);
t16 = cos(t6);
t17 = L5.*t15;
t18 = sin(th1);
t19 = sin(t2);
t20 = sin(t3);
t21 = sin(t4);
t22 = sin(t5);
t23 = sin(t6);
t24 = L1.*t18;
t25 = L2.*t19;
t26 = L3.*t20;
t27 = L4.*t21;
t28 = L5.*t22;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t7,t18,0.0,0.0,-t18,t7,0.0,0.0,0.0,0.0,1.0,0.0,t9+xb,t24+yb,zb,1.0,t8,t19,0.0,0.0,-t19,t8,0.0,0.0,0.0,0.0,1.0,0.0,t9+t10+xb,t24+t25+yb,zb,1.0,t11,t20,0.0,0.0,-t20,t11,0.0,0.0,0.0,0.0,1.0,0.0,t9+t10+t13+xb,t24+t25+t26+yb,zb,1.0,t12,t21,0.0,0.0,-t21,t12,0.0,0.0,0.0,0.0,1.0,0.0,t9+t10+t13+t14+xb,t24+t25+t26+t27+yb,zb,1.0,t15,t22,0.0,0.0,-t22,t15,0.0,0.0,0.0,0.0,1.0,0.0,t9+t10+t13+t14+t17+xb,t24+t25+t26+t27+t28+yb,zb,1.0,t16,t23,0.0,0.0,-t23,t16,0.0,0.0,0.0,0.0,1.0,0.0,t9+t10+t13+t14+t17+xb+L6.*t16,t24+t25+t26+t27+t28+yb+L6.*t23,zb,1.0],[4,4,7]);
