function g_st = fkFunc5(in1,in2,in3,effOffset)
%FKFUNC5
%    G_ST = FKFUNC5(IN1,IN2,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:32

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2;
t3 = th1+th2+th3;
t4 = th1+th2+th3+th4;
t5 = effOffset+th1+th2+th3+th4+th5;
t6 = cos(th1);
t7 = cos(t2);
t8 = L1.*t6;
t9 = L2.*t7;
t10 = cos(t3);
t11 = cos(t4);
t12 = L3.*t10;
t13 = L4.*t11;
t14 = sin(th1);
t15 = sin(t2);
t16 = sin(t3);
t17 = sin(t4);
t18 = sin(t5);
t19 = cos(t5);
t20 = L1.*t14;
t21 = L2.*t15;
t22 = L3.*t16;
t23 = L4.*t17;
t24 = th1+th2+th3+th4+th5;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t6,t14,0.0,0.0,-t14,t6,0.0,0.0,0.0,0.0,1.0,0.0,t8+xb,t20+yb,zb,1.0,t7,t15,0.0,0.0,-t15,t7,0.0,0.0,0.0,0.0,1.0,0.0,t8+t9+xb,t20+t21+yb,zb,1.0,t10,t16,0.0,0.0,-t16,t10,0.0,0.0,0.0,0.0,1.0,0.0,t8+t9+t12+xb,t20+t21+t22+yb,zb,1.0,t11,t17,0.0,0.0,-t17,t11,0.0,0.0,0.0,0.0,1.0,0.0,t8+t9+t12+t13+xb,t20+t21+t22+t23+yb,zb,1.0,t19,t18,0.0,0.0,-t18,t19,0.0,0.0,0.0,0.0,1.0,0.0,t8+t9+t12+t13+xb+L5.*cos(t24),t20+t21+t22+t23+yb+L5.*sin(t24),zb,1.0],[4,4,6]);
