function g_st = fkFunc4(in1,in2,in3,effOffset)
%FKFUNC4
%    G_ST = FKFUNC4(IN1,IN2,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:45:29

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2+th3+th4;
t3 = th1+th2;
t4 = th1+th2+th3;
t5 = cos(t2);
t6 = sin(effOffset);
t7 = sin(t2);
t8 = cos(effOffset);
t9 = cos(th1);
t10 = cos(t3);
t11 = L1.*t9;
t12 = L2.*t10;
t13 = cos(t4);
t14 = L3.*t13;
t15 = sin(th1);
t16 = sin(t3);
t17 = sin(t4);
t18 = t5.*t8;
t19 = t18-t6.*t7;
t20 = L1.*t15;
t21 = L2.*t16;
t22 = L3.*t17;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t9,t15,0.0,0.0,-t15,t9,0.0,0.0,0.0,0.0,1.0,0.0,t11+xb,t20+yb,zb,1.0,t10,t16,0.0,0.0,-t16,t10,0.0,0.0,0.0,0.0,1.0,0.0,t11+t12+xb,t20+t21+yb,zb,1.0,t13,t17,0.0,0.0,-t17,t13,0.0,0.0,0.0,0.0,1.0,0.0,t11+t12+t14+xb,t20+t21+t22+yb,zb,1.0,t19,t5.*t6+t7.*t8,0.0,0.0,-t5.*t6-t7.*t8,t19,0.0,0.0,0.0,0.0,1.0,0.0,t11+t12+t14+xb+L4.*t5,t20+t21+t22+yb+L4.*t7,zb,1.0],[4,4,5]);
