function g_st = fkFunc4(in1,in2,in3,effOffset)
%FKFUNC4
%    G_ST = FKFUNC4(IN1,IN2,IN3,EFFOFFSET)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:24

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
xb = in3(1,:);
yb = in3(2,:);
zb = in3(3,:);
t2 = th1+th2;
t3 = th1+th2+th3;
t4 = effOffset+th1+th2+th3+th4;
t5 = cos(th1);
t6 = cos(t2);
t7 = L1.*t5;
t8 = L2.*t6;
t9 = cos(t3);
t10 = L3.*t9;
t11 = sin(th1);
t12 = sin(t2);
t13 = sin(t3);
t14 = sin(t4);
t15 = cos(t4);
t16 = L1.*t11;
t17 = L2.*t12;
t18 = th1+th2+th3+th4;
t19 = L3.*t13;
g_st = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,xb,yb,zb,1.0,t5,t11,0.0,0.0,-t11,t5,0.0,0.0,0.0,0.0,1.0,0.0,t7+xb,t16+yb,zb,1.0,t6,t12,0.0,0.0,-t12,t6,0.0,0.0,0.0,0.0,1.0,0.0,t7+t8+xb,t16+t17+yb,zb,1.0,t9,t13,0.0,0.0,-t13,t9,0.0,0.0,0.0,0.0,1.0,0.0,t7+t8+t10+xb,t16+t17+t19+yb,zb,1.0,t15,t14,0.0,0.0,-t14,t15,0.0,0.0,0.0,0.0,1.0,0.0,t7+t8+t10+xb+L4.*cos(t18),t16+t17+t19+yb+L4.*sin(t18),zb,1.0],[4,4,5]);
