function ddf_torqueddth = ddf_torqueddthFunc1(th1,L1,in3)
%DDF_TORQUEDDTHFUNC1
%    DDF_TORQUEDDTH = DDF_TORQUEDDTHFUNC1(TH1,L1,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    29-Nov-2016 11:40:38

yb = in3(2,:);
t4 = conj(th1);
t2 = cos(t4);
t3 = L1.^2;
t5 = t2.^2;
t6 = t3.^2;
t7 = sin(t4);
ddf_torqueddth = t3.*t5.*3.4765291125e1-t5.*t6.*8.69132278125+t6.*t7.^2.*8.69132278125-L1.*t7.*(yb.*4.16925+L1.*t7.*4.16925).*8.3385;
