function ddfddeffOffset = ddfddeffOffsetFunc2(in1,in2,in3,effOffset,in5)
%DDFDDEFFOFFSETFUNC2
%    DDFDDEFFOFFSET = DDFDDEFFOFFSETFUNC2(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:18

th1 = in1(1,:);
th2 = in1(2,:);
thd = in5(3,:);
t2 = effOffset+th1+th2;
t4 = cos(t2);
t5 = cos(thd);
t6 = t4.*t5;
t7 = sin(t2);
t8 = sin(thd);
t9 = t7.*t8;
t3 = t6+t9;
ddfddeffOffset = t3.*(t6+t9-1.0).*-4.0+t3.^2.*4.0;
