function ddfddl = ddfddlFunc2(in1,in2,in3,in4)
%DDFDDLFUNC2
%    DDFDDL = DDFDDLFUNC2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:28

th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = sin(t4);
t6 = t3.*t5.*2.0;
t7 = cos(t4);
t8 = t2.*t7.*2.0;
t9 = t6+t8;
ddfddl = reshape([t2.^2.*2.0+t3.^2.*2.0,t9,t9,t5.^2.*2.0+t7.^2.*2.0],[2,2]);
