function ddfddeffOffset = ddfddeffOffsetFunc4(in1,in2,in3,effOffset,in5)
%DDFDDEFFOFFSETFUNC4
%    DDFDDEFFOFFSET = DDFDDEFFOFFSETFUNC4(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:30

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
thd = in5(3,:);
t2 = effOffset+th1+th2+th3+th4;
t3 = cos(thd);
t4 = cos(t2);
t5 = t3.*t4;
t6 = sin(t2);
t7 = sin(thd);
t8 = t6.*t7;
t9 = t5+t8;
ddfddeffOffset = t9.*(t5+t8-1.0).*-4.0+t9.^2.*4.0;
