function ddfddrb = ddfddrbFunc2(in1,in2,in3,effOffset,in5)
%DDFDDRBFUNC2
%    DDFDDRB = DDFDDRBFUNC2(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:06

ddfddrb = reshape([2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0],[3,3]);
