function ddfddrb = ddfddrbFunc6(in1,in2,in3,effOffset,in5)
%DDFDDRBFUNC6
%    DDFDDRB = DDFDDRBFUNC6(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Nov-2016 14:24:03

ddfddrb = reshape([2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0],[3,3]);
