function ddfddth = ddfddthFunc2(in1,in2,in3,in4)
%DDFDDTHFUNC2
%    DDFDDTH = DDFDDTHFUNC2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:28

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
thd = in4(3,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = L2.*t3;
t5 = cos(th1);
t6 = L1.*t5;
t7 = sin(t2);
t8 = L2.*t7;
t9 = sin(th1);
t10 = L1.*t9;
t11 = t4+t6;
t14 = sin(thd);
t15 = t7.*t14;
t16 = cos(thd);
t17 = t3.*t16;
t12 = t15+t17;
t13 = t8+t10;
t18 = t12.^2;
t19 = t18.*4.0;
t20 = t15+t17-1.0;
t21 = t8+t10+yb-yd;
t22 = t4+t6+xb-xd;
t23 = L2.*t3.*t11.*2.0;
t24 = L2.*t7.*t13.*2.0;
t27 = t12.*t20.*4.0;
t28 = L2.*t7.*t21.*2.0;
t29 = L2.*t3.*t22.*2.0;
t25 = t19+t23+t24-t27-t28-t29;
t26 = L2.^2;
ddfddth = reshape([t19-t12.*t20.*4.0-t11.*t22.*2.0-t13.*t21.*2.0+t11.^2.*2.0+t13.^2.*2.0,t25,t25,t19-t27-t28-t29+t3.^2.*t26.*2.0+t7.^2.*t26.*2.0],[2,2]);
