function ddfddth = ddfddthFunc1(th1,L1,in3,effOffset,in5)
%DDFDDTHFUNC1
%    DDFDDTH = DDFDDTHFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:13

thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = cos(th1);
t3 = L1.^2;
t4 = sin(th1);
t5 = effOffset+th1;
t7 = cos(t5);
t8 = cos(thd);
t9 = t7.*t8;
t10 = sin(t5);
t11 = sin(thd);
t12 = t10.*t11;
t6 = t9+t12;
ddfddth = t6.*(t9+t12-1.0).*-4.0+t2.^2.*t3.*2.0+t3.*t4.^2.*2.0+t6.^2.*4.0-L1.*t2.*(xb-xd+L1.*t2).*2.0-L1.*t4.*(yb-yd+L1.*t4).*2.0;
