function ddfddth = ddfddthFunc1(th1,L1,in3,in4)
%DDFDDTHFUNC1
%    DDFDDTH = DDFDDTHFUNC1(TH1,L1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:26

thd = in4(3,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t2 = cos(th1);
t3 = L1.^2;
t4 = sin(th1);
t5 = cos(thd);
t6 = t2.*t5;
t7 = sin(thd);
t8 = t4.*t7;
t9 = t6+t8;
ddfddth = t9.*(t6+t8-1.0).*-4.0+t2.^2.*t3.*2.0+t3.*t4.^2.*2.0+t9.^2.*4.0-L1.*t2.*(xb-xd+L1.*t2).*2.0-L1.*t4.*(yb-yd+L1.*t4).*2.0;
