function ddfddth = ddfddthFunc2(in1,in2,in3,effOffset,in5)
%DDFDDTHFUNC2
%    DDFDDTH = DDFDDTHFUNC2(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:17

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = L2.*t3;
t5 = cos(th1);
t6 = L1.*t5;
t7 = sin(t2);
t8 = L2.*t7;
t9 = sin(th1);
t10 = L1.*t9;
t11 = effOffset+th1+th2;
t13 = cos(t11);
t14 = cos(thd);
t15 = t13.*t14;
t16 = sin(t11);
t17 = sin(thd);
t18 = t16.*t17;
t12 = t15+t18;
t19 = t4+t6;
t20 = t8+t10;
t21 = t12.^2;
t22 = t21.*4.0;
t23 = t15+t18-1.0;
t24 = t8+t10+yb-yd;
t25 = t4+t6+xb-xd;
t26 = L2.*t3.*t19.*2.0;
t27 = L2.*t7.*t20.*2.0;
t30 = t12.*t23.*4.0;
t31 = L2.*t7.*t24.*2.0;
t32 = L2.*t3.*t25.*2.0;
t28 = t22+t26+t27-t30-t31-t32;
t29 = L2.^2;
ddfddth = reshape([t22-t12.*t23.*4.0-t19.*t25.*2.0-t20.*t24.*2.0+t19.^2.*2.0+t20.^2.*2.0,t28,t28,t22-t30-t31-t32+t3.^2.*t29.*2.0+t7.^2.*t29.*2.0],[2,2]);
