function ddfddl = ddfddlFunc3(in1,in2,in3,effOffset,in5)
%DDFDDLFUNC3
%    DDFDDL = DDFDDLFUNC3(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:22

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = th1+th2+th3;
t6 = sin(t4);
t7 = t3.*t6.*2.0;
t8 = cos(t4);
t9 = t2.*t8.*2.0;
t10 = t7+t9;
t11 = cos(t5);
t12 = sin(t5);
t13 = t2.*t11.*2.0;
t14 = t3.*t12.*2.0;
t15 = t13+t14;
t16 = t8.*t11.*2.0;
t17 = t6.*t12.*2.0;
t18 = t16+t17;
ddfddl = reshape([t2.^2.*2.0+t3.^2.*2.0,t10,t15,t10,t6.^2.*2.0+t8.^2.*2.0,t18,t15,t18,t11.^2.*2.0+t12.^2.*2.0],[3,3]);
