function ddfddth = ddfddthFunc1(th1,L1,in3,effOffset,in5)
%DDFDDTHFUNC1
%    DDFDDTH = DDFDDTHFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:02

thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = cos(effOffset);
t3 = sin(th1);
t4 = cos(th1);
t5 = sin(effOffset);
t6 = cos(thd);
t7 = t2.*t4;
t15 = t3.*t5;
t8 = t7-t15;
t9 = t6.*t8;
t10 = sin(thd);
t11 = t2.*t3;
t12 = t4.*t5;
t13 = t11+t12;
t14 = t10.*t13;
t16 = t9+t14;
t17 = L1.^2;
ddfddth = t16.*(t9+t14-1.0).*-4.0+t3.^2.*t17.*2.0+t4.^2.*t17.*2.0+t16.^2.*4.0-L1.*t4.*(xb-xd+L1.*t4).*2.0-L1.*t3.*(yb-yd+L1.*t3).*2.0;
