function ddfddeffOffset = ddfddeffOffsetFunc1(th1,L1,in3,effOffset,in5)
%DDFDDEFFOFFSETFUNC1
%    DDFDDEFFOFFSET = DDFDDEFFOFFSETFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:14

thd = in5(3,:);
t2 = effOffset+th1;
t4 = cos(t2);
t5 = cos(thd);
t6 = t4.*t5;
t7 = sin(t2);
t8 = sin(thd);
t9 = t7.*t8;
t3 = t6+t9;
ddfddeffOffset = t3.*(t6+t9-1.0).*-4.0+t3.^2.*4.0;
