function ddfddeffOffset = ddfddeffOffsetFunc5(in1,in2,in3,effOffset,in5)
%DDFDDEFFOFFSETFUNC5
%    DDFDDEFFOFFSET = DDFDDEFFOFFSETFUNC5(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:41

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
thd = in5(3,:);
t2 = effOffset+th1+th2+th3+th4+th5;
t4 = cos(t2);
t5 = cos(thd);
t6 = t4.*t5;
t7 = sin(t2);
t8 = sin(thd);
t9 = t7.*t8;
t3 = t6+t9;
ddfddeffOffset = t3.*(t6+t9-1.0).*-4.0+t3.^2.*4.0;
