function ddfddrb = ddfddrbFunc1(th1,L1,in3,effOffset,in5)
%DDFDDRBFUNC1
%    DDFDDRB = DDFDDRBFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:45:18

ddfddrb = reshape([2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0],[3,3]);
