function ddfddeffOffset = ddfddeffOffsetFunc1(th1,L1,in3,effOffset,in5)
%DDFDDEFFOFFSETFUNC1
%    DDFDDEFFOFFSET = DDFDDEFFOFFSETFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:45:18

thd = in5(3,:);
t2 = cos(effOffset);
t3 = sin(th1);
t4 = cos(th1);
t5 = sin(effOffset);
t6 = cos(thd);
t7 = t2.*t4;
t15 = t3.*t5;
t8 = t7-t15;
t9 = t6.*t8;
t10 = sin(thd);
t11 = t2.*t3;
t12 = t4.*t5;
t13 = t11+t12;
t14 = t10.*t13;
t16 = t9+t14;
ddfddeffOffset = t16.*(t9+t14-1.0).*-4.0+t16.^2.*4.0;
