function dfdeffOffset = dfdeffOffsetFunc4(in1,in2,in3,effOffset,in5)
%DFDEFFOFFSETFUNC4
%    DFDEFFOFFSET = DFDEFFOFFSETFUNC4(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:16

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
thd = in5(3,:);
t2 = th1+th2+th3+th4;
t3 = cos(t2);
t4 = sin(effOffset);
t5 = sin(t2);
t6 = cos(effOffset);
t7 = cos(thd);
t8 = t3.*t4;
t9 = t5.*t6;
t10 = t8+t9;
t11 = sin(thd);
t12 = t3.*t6;
t15 = t4.*t5;
t13 = t12-t15;
t14 = t7.*t10;
t16 = t14-t11.*t13;
t17 = t7.*t13;
t18 = t10.*t11;
dfdeffOffset = t16.*(t17+t18).*4.0-t16.*(t17+t18-1.0).*4.0;
