function dfdl = dfdlFunc1(th1,L1,in3,in4)
%DFDLFUNC1
%    DFDL = DFDLFUNC1(TH1,L1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:26

xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t2 = cos(th1);
t3 = sin(th1);
dfdl = t2.*(xb-xd+L1.*t2).*2.0+t3.*(yb-yd+L1.*t3).*2.0;
