function dfdl = dfdlFunc1(th1,L1,in3,effOffset,in5)
%DFDLFUNC1
%    DFDL = DFDLFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:01

xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = cos(th1);
t3 = sin(th1);
dfdl = t2.*(xb-xd+L1.*t2).*2.0+t3.*(yb-yd+L1.*t3).*2.0;
