function dfdl = dfdlFunc6(in1,in2,in3,in4)
%DFDLFUNC6
%    DFDL = DFDLFUNC6(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:44

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
L6 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
th6 = in1(6,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t2 = sin(th1);
t3 = th1+th2+th3+th4+th5+th6;
t4 = th1+th2+th3+th4;
t5 = th1+th2;
t6 = cos(th1);
t7 = th1+th2+th3+th4+th5;
t8 = th1+th2+th3;
t9 = cos(t5);
t10 = cos(t3);
t11 = L6.*t10;
t12 = cos(t4);
t13 = L4.*t12;
t14 = L2.*t9;
t15 = L1.*t6;
t16 = cos(t7);
t17 = L5.*t16;
t18 = cos(t8);
t19 = L3.*t18;
t20 = t11+t13+t14+t15+t17+t19+xb-xd;
t21 = sin(t5);
t22 = sin(t3);
t23 = L6.*t22;
t24 = sin(t4);
t25 = L4.*t24;
t26 = L2.*t21;
t27 = L1.*t2;
t28 = sin(t7);
t29 = L5.*t28;
t30 = sin(t8);
t31 = L3.*t30;
t32 = t23+t25+t26+t27+t29+t31+yb-yd;
dfdl = [t6.*t20.*2.0+t2.*t32.*2.0,t9.*t20.*2.0+t21.*t32.*2.0,t18.*t20.*2.0+t30.*t32.*2.0,t12.*t20.*2.0+t24.*t32.*2.0,t16.*t20.*2.0+t28.*t32.*2.0,t10.*t20.*2.0+t22.*t32.*2.0];
