function dfdl = dfdlFunc5(in1,in2,in3,in4)
%DFDLFUNC5
%    DFDL = DFDLFUNC5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:37

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t2 = cos(th1);
t3 = th1+th2+th3+th4;
t4 = th1+th2;
t5 = sin(th1);
t6 = th1+th2+th3+th4+th5;
t7 = th1+th2+th3;
t8 = cos(t4);
t9 = cos(t3);
t10 = L4.*t9;
t11 = L2.*t8;
t12 = L1.*t2;
t13 = cos(t6);
t14 = L5.*t13;
t15 = cos(t7);
t16 = L3.*t15;
t17 = t10+t11+t12+t14+t16+xb-xd;
t18 = sin(t4);
t19 = sin(t3);
t20 = L4.*t19;
t21 = L2.*t18;
t22 = L1.*t5;
t23 = sin(t6);
t24 = L5.*t23;
t25 = sin(t7);
t26 = L3.*t25;
t27 = t20+t21+t22+t24+t26+yb-yd;
dfdl = [t2.*t17.*2.0+t5.*t27.*2.0,t8.*t17.*2.0+t18.*t27.*2.0,t15.*t17.*2.0+t25.*t27.*2.0,t9.*t17.*2.0+t19.*t27.*2.0,t13.*t17.*2.0+t23.*t27.*2.0];
