function dfdl = dfdlFunc3(in1,in2,in3,effOffset,in5)
%DFDLFUNC3
%    DFDL = DFDLFUNC3(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:09

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = cos(th1);
t3 = th1+th2;
t4 = sin(th1);
t5 = th1+th2+th3;
t6 = cos(t3);
t7 = L2.*t6;
t8 = L1.*t2;
t9 = cos(t5);
t10 = L3.*t9;
t11 = t7+t8+t10+xb-xd;
t12 = sin(t3);
t13 = L2.*t12;
t14 = L1.*t4;
t15 = sin(t5);
t16 = L3.*t15;
t17 = t13+t14+t16+yb-yd;
dfdl = [t2.*t11.*2.0+t4.*t17.*2.0,t6.*t11.*2.0+t12.*t17.*2.0,t9.*t11.*2.0+t15.*t17.*2.0];
