function dfdrb = dfdrbFunc5(in1,in2,in3,effOffset,in5)
%DFDRBFUNC5
%    DFDRB = DFDRBFUNC5(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:45:41

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = th1+th2+th3+th4;
t3 = th1+th2;
t4 = th1+th2+th3+th4+th5;
t5 = th1+th2+th3;
dfdrb = [xb.*2.0-xd.*2.0+L2.*cos(t3).*2.0+L4.*cos(t2).*2.0+L3.*cos(t5).*2.0+L5.*cos(t4).*2.0+L1.*cos(th1).*2.0,yb.*2.0-yd.*2.0+L2.*sin(t3).*2.0+L4.*sin(t2).*2.0+L3.*sin(t5).*2.0+L5.*sin(t4).*2.0+L1.*sin(th1).*2.0,0.0];
