function dfdrb = dfdrbFunc1(th1,L1,in3,effOffset,in5)
%DFDRBFUNC1
%    DFDRB = DFDRBFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:01

xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
dfdrb = [xb.*2.0-xd.*2.0+L1.*cos(th1).*2.0,yb.*2.0-yd.*2.0+L1.*sin(th1).*2.0,0.0];
