function dfdth = dfdthFunc3(in1,in2,in3,effOffset,in5)
%DFDTHFUNC3
%    DFDTH = DFDTHFUNC3(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:20

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = effOffset+th1+th2+th3;
t3 = cos(t2);
t4 = sin(thd);
t5 = sin(t2);
t6 = cos(thd);
t7 = t3.*t4;
t26 = t5.*t6;
t8 = t7-t26;
t9 = t3.*t6;
t10 = t4.*t5;
t11 = th1+th2;
t12 = th1+th2+th3;
t13 = cos(t11);
t14 = L2.*t13;
t15 = cos(th1);
t16 = L1.*t15;
t17 = cos(t12);
t18 = L3.*t17;
t19 = sin(t11);
t20 = L2.*t19;
t21 = sin(th1);
t22 = L1.*t21;
t23 = sin(t12);
t24 = L3.*t23;
t25 = t9+t10;
t27 = t9+t10-1.0;
t28 = t8.*t27.*4.0;
t29 = t14+t16+t18+xb-xd;
t30 = t20+t22+t24+yb-yd;
dfdth = [t28-t8.*t25.*4.0+t30.*(t14+t16+t18).*2.0-t29.*(t20+t22+t24).*2.0,t28+t30.*(t14+t18).*2.0-t29.*(t20+t24).*2.0-t8.*t25.*4.0,t28-t8.*t25.*4.0+L3.*t17.*t30.*2.0-L3.*t23.*t29.*2.0];
