function dfdth = dfdthFunc1(th1,L1,in3,in4)
%DFDTHFUNC1
%    DFDTH = DFDTHFUNC1(TH1,L1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:26

thd = in4(3,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t2 = cos(th1);
t3 = sin(thd);
t4 = cos(thd);
t5 = sin(th1);
t6 = t2.*t3;
t7 = t6-t4.*t5;
t8 = t2.*t4;
t9 = t3.*t5;
dfdth = t7.*(t8+t9).*-4.0+t7.*(t8+t9-1.0).*4.0-L1.*t5.*(xb-xd+L1.*t2).*2.0+L1.*t2.*(yb-yd+L1.*t5).*2.0;
