function dfdth = dfdthFunc2(in1,in2,in3,effOffset,in5)
%DFDTHFUNC2
%    DFDTH = DFDTHFUNC2(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:16

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = L2.*t3;
t5 = cos(th1);
t6 = L1.*t5;
t7 = sin(t2);
t8 = L2.*t7;
t9 = sin(th1);
t10 = L1.*t9;
t11 = effOffset+th1+th2;
t12 = cos(t11);
t13 = sin(thd);
t14 = sin(t11);
t15 = cos(thd);
t16 = t12.*t13;
t21 = t14.*t15;
t17 = t16-t21;
t18 = t12.*t15;
t19 = t13.*t14;
t20 = t18+t19;
t22 = t18+t19-1.0;
t23 = t17.*t22.*4.0;
t24 = t8+t10+yb-yd;
t25 = t4+t6+xb-xd;
dfdth = [t23+t24.*(t4+t6).*2.0-t25.*(t8+t10).*2.0-t17.*t20.*4.0,t23-t17.*t20.*4.0+L2.*t3.*t24.*2.0-L2.*t7.*t25.*2.0];
