function dfdth = dfdthFunc4(in1,in2,in3,effOffset,in5)
%DFDTHFUNC4
%    DFDTH = DFDTHFUNC4(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:25

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = effOffset+th1+th2+th3+th4;
t3 = sin(t2);
t4 = cos(thd);
t5 = sin(thd);
t6 = cos(t2);
t7 = t3.*t4;
t31 = t5.*t6;
t8 = t7-t31;
t9 = t4.*t6;
t10 = t3.*t5;
t11 = th1+th2+th3+th4;
t12 = th1+th2;
t13 = th1+th2+th3;
t14 = cos(t11);
t15 = L4.*t14;
t16 = cos(t12);
t17 = L2.*t16;
t18 = cos(th1);
t19 = L1.*t18;
t20 = cos(t13);
t21 = L3.*t20;
t22 = sin(t11);
t23 = L4.*t22;
t24 = sin(t12);
t25 = L2.*t24;
t26 = sin(th1);
t27 = L1.*t26;
t28 = sin(t13);
t29 = L3.*t28;
t30 = t9+t10;
t32 = t8.*t30.*4.0;
t33 = t9+t10-1.0;
t34 = t15+t17+t19+t21+xb-xd;
t35 = t23+t25+t27+t29+yb-yd;
dfdth = [t32+t35.*(t15+t17+t19+t21).*2.0-t34.*(t23+t25+t27+t29).*2.0-t8.*t33.*4.0,t32-t8.*t33.*4.0+t35.*(t15+t17+t21).*2.0-t34.*(t23+t25+t29).*2.0,t32+t35.*(t15+t21).*2.0-t34.*(t23+t29).*2.0-t8.*t33.*4.0,t32-t8.*t33.*4.0+L4.*t14.*t35.*2.0-L4.*t22.*t34.*2.0];
