function dfdth = dfdthFunc2(in1,in2,in3,effOffset,in5)
%DFDTHFUNC2
%    DFDTH = DFDTHFUNC2(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:45:20

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = L2.*t3;
t5 = cos(th1);
t6 = L1.*t5;
t7 = sin(t2);
t8 = L2.*t7;
t9 = sin(th1);
t10 = L1.*t9;
t11 = sin(effOffset);
t12 = cos(effOffset);
t13 = cos(thd);
t14 = t3.*t11;
t15 = t7.*t12;
t16 = t14+t15;
t17 = sin(thd);
t18 = t3.*t12;
t21 = t7.*t11;
t19 = t18-t21;
t20 = t13.*t16;
t26 = t17.*t19;
t22 = t20-t26;
t23 = t13.*t19;
t24 = t16.*t17;
t25 = t23+t24;
t27 = t22.*t25.*4.0;
t28 = t23+t24-1.0;
t29 = t8+t10+yb-yd;
t30 = t4+t6+xb-xd;
dfdth = [t27+t29.*(t4+t6).*2.0-t30.*(t8+t10).*2.0-t22.*t28.*4.0,t27-t22.*t28.*4.0+L2.*t3.*t29.*2.0-L2.*t7.*t30.*2.0];
