function f_tau = f_torqueFunc2(in1,in2,in3)
%F_TORQUEFUNC2
%    F_TAU = F_TORQUEFUNC2(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Nov-2016 12:02:50

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
yb = in3(2,:);
t2 = conj(th1);
t5 = conj(th2);
t6 = t2+t5;
t10 = yb.*4.16925;
t13 = sin(t2);
t3 = t10+L1.*t13.*4.16925+L2.*sin(t6).*4.16925;
t4 = L2.^2;
t7 = cos(t6);
t8 = cos(t2);
t11 = L1.*4.16925;
t12 = t11+3.5316;
t14 = L1.*(1.7e1./4.0e1);
t15 = t14+9.0./2.5e1;
t16 = L1.*(9.0./2.5e1);
t17 = L1.^2;
t18 = t17.*(1.7e1./8.0e1);
t19 = t16+t18;
t20 = 1.0./t15;
t9 = L2.*(L1.*t8+L2.*t7.*(1.0./2.0)).*4.16925+t8.*t12.*t19.*t20;
t21 = t10+L2.*t13.*4.16925+t12.*(t13-t13.*1.0./t15.^2.*t19.*(1.7e1./4.0e1))+t13.*t19.*t20.*4.16925;
f_tau = t4.^2.*t7.^2.*4.345661390625+t3.^2+t9.^2+t21.^2;
