function f_tau = f_torqueFunc1(th1,L1,in3)
%F_TORQUEFUNC1
%    F_TAU = F_TORQUEFUNC1(TH1,L1,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 10:04:26

yb = in3(2,:);
t4 = conj(th1);
t2 = yb.*4.16925+L1.*sin(t4).*4.16925;
t3 = L1.^2;
t5 = cos(t4);
f_tau = t3.^2.*t5.^2.*4.345661390625+t2.^2;
