function f = fFunc1(th1,L1,in3,effOffset,in5)
%FFUNC1
%    F = FFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:00

thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = cos(effOffset);
t3 = cos(th1);
t4 = sin(effOffset);
t5 = sin(th1);
t7 = cos(thd);
t8 = t2.*t3;
t9 = t4.*t5;
t10 = t8-t9;
t11 = sin(thd);
t12 = t2.*t5;
t13 = t3.*t4;
t14 = t12+t13;
t6 = t7.*t14-t10.*t11;
t15 = t7.*t10+t11.*t14-1.0;
t16 = xb-xd+L1.*t3;
t17 = yb-yd+L1.*t5;
f = t6.^2.*2.0+t15.^2.*2.0+t16.^2+t17.^2;
