function f = fFunc5(in1,in2,in3,effOffset,in5)
%FFUNC5
%    F = FFUNC5(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:23

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = th1+th2+th3+th4+th5;
t3 = cos(t2);
t4 = cos(effOffset);
t5 = sin(t2);
t6 = sin(effOffset);
t8 = cos(thd);
t9 = t3.*t4;
t10 = t5.*t6;
t11 = t9-t10;
t12 = sin(thd);
t13 = t3.*t6;
t14 = t4.*t5;
t15 = t13+t14;
t7 = t8.*t15-t11.*t12;
t16 = t8.*t11+t12.*t15-1.0;
t18 = th1+th2+th3+th4;
t19 = th1+th2;
t20 = th1+th2+th3;
t17 = xb-xd+L5.*t3+L2.*cos(t19)+L4.*cos(t18)+L3.*cos(t20)+L1.*cos(th1);
t21 = yb-yd+L5.*t5+L2.*sin(t19)+L4.*sin(t18)+L3.*sin(t20)+L1.*sin(th1);
f = t7.^2.*2.0+t16.^2.*2.0+t17.^2+t21.^2;
