function f = fFunc6(in1,in2,in3,effOffset,in5)
%FFUNC6
%    F = FFUNC6(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Nov-2016 14:23:47

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
L6 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
th6 = in1(6,:);
thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t3 = th1+th2+th3+th4+th5+th6;
t4 = th1+th2+th3+th4;
t5 = th1+th2;
t6 = th1+th2+th3+th4+th5;
t7 = th1+th2+th3;
t10 = sin(t3);
t2 = yb-yd+L6.*t10+L2.*sin(t5)+L4.*sin(t4)+L3.*sin(t7)+L5.*sin(t6)+L1.*sin(th1);
t9 = cos(t3);
t8 = xb-xd+L6.*t9+L2.*cos(t5)+L4.*cos(t4)+L3.*cos(t7)+L5.*cos(t6)+L1.*cos(th1);
t11 = cos(effOffset);
t12 = sin(effOffset);
t14 = cos(thd);
t15 = t9.*t11;
t16 = t10.*t12;
t17 = t15-t16;
t18 = sin(thd);
t19 = t9.*t12;
t20 = t10.*t11;
t21 = t19+t20;
t13 = t14.*t21-t17.*t18;
t22 = t14.*t17+t18.*t21-1.0;
f = t2.^2+t8.^2+t13.^2.*2.0+t22.^2.*2.0;
