function f = fFunc2(in1,in2,in3,effOffset,in5)
%FFUNC2
%    F = FFUNC2(IN1,IN2,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 18:59:04

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t3 = th1+th2;
t4 = sin(t3);
t2 = yb-yd+L2.*t4+L1.*sin(th1);
t5 = cos(t3);
t6 = cos(effOffset);
t7 = sin(effOffset);
t9 = cos(thd);
t10 = t5.*t6;
t11 = t4.*t7;
t12 = t10-t11;
t13 = sin(thd);
t14 = t5.*t7;
t15 = t4.*t6;
t16 = t14+t15;
t8 = t9.*t16-t12.*t13;
t17 = t9.*t12+t13.*t16-1.0;
t18 = xb-xd+L2.*t5+L1.*cos(th1);
f = t2.^2+t8.^2.*2.0+t17.^2.*2.0+t18.^2;
