function f = fFunc1(th1,L1,in3,effOffset,in5)
%FFUNC1
%    F = FFUNC1(TH1,L1,IN3,EFFOFFSET,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Nov-2016 17:00:12

thd = in5(3,:);
xb = in3(1,:);
xd = in5(1,:);
yb = in3(2,:);
yd = in5(2,:);
t2 = effOffset+th1;
t4 = cos(t2);
t5 = cos(thd);
t6 = sin(t2);
t7 = sin(thd);
t3 = t4.*t7-t5.*t6;
t8 = t4.*t5+t6.*t7-1.0;
t9 = xb-xd+L1.*cos(th1);
t10 = yb-yd+L1.*sin(th1);
f = t3.^2.*2.0+t8.^2.*2.0+t9.^2+t10.^2;
