function f = fFunc6(in1,in2,in3,in4)
%FFUNC6
%    F = FFUNC6(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 09:25:43

L1 = in2(1,:);
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
L6 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
th6 = in1(6,:);
thd = in4(3,:);
xb = in3(1,:);
xd = in4(1,:);
yb = in3(2,:);
yd = in4(2,:);
t3 = th1+th2+th3+th4+th5+th6;
t4 = sin(t3);
t10 = th1+th2+th3+th4;
t11 = th1+th2;
t12 = th1+th2+th3+th4+th5;
t13 = th1+th2+th3;
t2 = yb-yd+L6.*t4+L2.*sin(t11)+L4.*sin(t10)+L3.*sin(t13)+L5.*sin(t12)+L1.*sin(th1);
t6 = cos(t3);
t7 = cos(thd);
t8 = sin(thd);
t5 = -t4.*t7+t6.*t8;
t9 = t4.*t8+t6.*t7-1.0;
t14 = xb-xd+L6.*t6+L2.*cos(t11)+L4.*cos(t10)+L3.*cos(t13)+L5.*cos(t12)+L1.*cos(th1);
f = t2.^2+t5.^2.*2.0+t9.^2.*2.0+t14.^2;
