function tau = g_torqueFunc2(in1,in2,in3)
%G_TORQUEFUNC2
%    TAU = G_TORQUEFUNC2(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 10:04:27

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
yb = in3(2,:);
t2 = conj(th1);
t3 = cos(t2);
t4 = conj(th2);
t5 = t2+t4;
t6 = cos(t5);
t7 = L1.*4.16925;
t8 = t7+3.5316;
t9 = sin(t2);
t10 = L1.*(1.7e1./4.0e1);
t11 = t10+9.0./2.5e1;
t12 = L1.*(9.0./2.5e1);
t13 = L1.^2;
t14 = t13.*(1.7e1./8.0e1);
t15 = t12+t14;
t16 = 1.0./t11;
t17 = yb.*4.16925;
tau = [L2.*(L1.*t3+L2.*t6.*(1.0./2.0)).*4.16925+t3.*t8.*t15.*t16;L2.^2.*t6.*2.084625;t17+L2.*t9.*4.16925+t8.*(t9-t9.*1.0./t11.^2.*t15.*(1.7e1./4.0e1))+t9.*t15.*t16.*4.16925;t17+L1.*t9.*4.16925+L2.*sin(t5).*4.16925];
