function tau = g_torqueFunc1(th1,L1,in3)
%G_TORQUEFUNC1
%    TAU = G_TORQUEFUNC1(TH1,L1,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Nov-2016 10:04:26

yb = in3(2,:);
t2 = conj(th1);
tau = [L1.^2.*cos(t2).*2.084625;yb.*4.16925+L1.*sin(t2).*4.16925];
